[project]
name = "seroprojectcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "pandas>=2.3.3",
    "pathlib>=1.0.1",
    "streamlit>=1.51.0",
]
